# Generated by Django 4.0.4 on 2022-09-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_projectdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='description',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='difficulties',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
