# Generated by Django 4.0.4 on 2022-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_projectdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
