# Generated by Django 4.0.4 on 2022-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_rename_images_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='order_of_display',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
