# Generated by Django 4.0.4 on 2022-09-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_projectdetails_order_of_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='technology',
            field=models.ManyToManyField(to='portfolio_app.skill'),
        ),
    ]
