# Generated by Django 4.0.4 on 2022-09-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0014_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
