# Generated by Django 4.0.4 on 2022-09-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0016_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
